build:
    image: golang
    environment:
        - ENVIRONMENT=drone
        - REPO_OWNER=vokal
        - REPO_NAME=vip
    commands:
        - go get
        - go get -t
        - go build
        - go test -gocheck.v -coverprofile=coverage.txt -covermode=count
        - cd fetch && go test -v -coverprofile=coverage.txt -covermode=count
        - cd ..
        - cat fetch/coverage.txt >> coverage.txt && rm fetch/coverage.txt
        - cat coverage.txt
        - export CVR_URL="https://cvr.vokal.io/coverage?commit=$DRONE_COMMIT&owner=$REPO_OWNER&repo=$REPO_NAME&coveragetype=gocover"
        - curl -F coverage=@coverage.txt $CVR_URL
publish:
    docker:
        username: vokal
        password: $$dockerPass
        email: docker@vokal.io
        repo: vokal/vip
        when:
            branch: master
